- name: create user, copy setup file and install haproxy
  block: 
    - name: create user haproxy if not exist
      ansible.builtin.user:
        name: haproxy
        password: "{{ haproxy_passwd }}"
      ignore_errors: yes

    - name: create haproxy folder
      shell: |
        mkdir -p /u02/haproxy/haproxy;
        chown -R haproxy:haproxy /u02/haproxy/haproxy;
      ignore_errors: yes
      
    - name: Copy file with owner and permissions
      copy:
        src: "{{ item }}"
        dest: /u02/haproxy/haproxy/
        owner: haproxy
        group: haproxy
      with_fileglob: "*.rpm"
      register: rpm_setup_files

    - name: Allow user to have sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^haproxy'
        line: 'haproxy ALL=(ALL) ALL'
        validate: visudo -cf %s

    - name: install haproxy
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ rpm_setup_files.results | map(attribute='dest') | list }}"

  become: true
  become_user: root
  tags:
    - setup