---
# This playbook contains common plays that will be run on all nodes.

- name: create user vt_admin, oam if not exist
  shell: |
    /usr/sbin/useradd vt_admin;
    /usr/sbin/useradd oam;
    /usr/sbin/groupname oam;
    /usr/sbin/groupname vt_admin;
    /usr/sbin/usermod -a -G oam vt_admin;
  ignore_errors: yes

- name: get ip mpbn of remote host
  become_user: root
  shell: /sbin/ifconfig bond1 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*'
  register: mpbn_ip_rm_host