- name: runtime configuration
  block: 
    - name: "wait for port to be available"
      wait_for:
        host: "{{ server_ip }}"
        port: "{{ server_port }}"
        timeout: 10

    - name: create scripted field kibana
      uri:
        url: http://{{ server_ip }}:{{ server_port }}/api/saved_objects/index-pattern/{{ item.name }}
        method: POST
        user: "elastic"
        password: "{{ bootstrap_password }}"
        body: "{{ lookup('template','create_scripted_field.jinja2') | to_json }}"
        body_format: json
        headers:
          Content-Type: "application/json"
          kbn-xsrf: "true"
      with_items: "{{ process_index_setup }}"

  become: true
  become_user: root
  tags:
    - scripted_field_setup