- name: configure system
  block:
    - name: edit kibana.yml
      template:
        src: kibana.jinja2
        dest: /etc/kibana/kibana.yml
        owner: kibana
        group: kibana
        mode: 0644 

    - name: create data folder if not exist
      file:
        path: /u01/kibana/kibana/data/
        state: directory
        owner: kibana
        group: kibana
        mode: 0754
    
    - name: create logs folder if not exist
      file:
        path: /u02/kibana/kibana/logs/
        state: directory
        owner: kibana
        group: kibana
        mode: 0754
      notify:
        - reload systemd
        - enable start-up
        - restart kibana
    
    - name: Flush handlers (force reload-restart elastic search)
      meta: flush_handlers

  become: true
  become_user: root
  tags:
    - sysconfig
