- name: Check list setup
  block:
    - name: make sure elastic search is up
      wait_for:
        host: "{{ master_node }}"
        port: "{{ http_port }}"
        timeout: 30
        
    - name: Check policy
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_ilm/policy/policy__del_after_{{ item }}
        method: GET
        user: "elastic"
        password: "{{ bootstrap_password }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
      retries: 3
      delay: 10
      with_items: "{{ policy_setup }}"

    - name: Check index
      uri:
        url: http://{{ master_node }}:{{ http_port }}/{{ item.name }}*/_ilm/explain
        method: GET
        user: "elastic"
        password: "{{ bootstrap_password }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
      register: index_result
      retries: 3
      delay: 10
      with_items: "{{ process_index_setup }}"

    - name: print msg
      debug: "{{ index_result | json_query([*].{managed})}}"
    - name: check index template
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_index_template/template__li_ocs_{{ item | regex_replace('[^0-9]','') }}days
        method: GET
        user: "elastic"
        password: "{{ bootstrap_password }}"
        force_basic_auth: yes
        status_code: 200
      with_items: "{{ policy_setup }}"
    
    - name: check shards
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_index_template/template__{{ item.name }}
        method: GET
        user: "elastic"
        password: "{{ bootstrap_password }}"
        force_basic_auth: yes
        status_code: 200
      with_items: "{{ process_index_setup }}"

    - name: check mlockall
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_nodes?filter_path=**.mlockall
        method: GET
        user: "elastic"
        password: "{{ bootstrap_password }}"
        force_basic_auth: yes
        status_code: 200
      with_items: "{{ process_index_setup }}"
  become: true
  become_user: root
  tags:
    - init_user