---
# tasks file for elastic search

- name: Include task list in play
  import_tasks: setup.yml
- name: Include task list in play
  import_tasks: sysconfig.yml
- name: Include task list in play
  import_tasks: init_user.yml
  when: mpbn_ip_rm_host.stdout == "master_node"
- name: Include task list in play
  import_tasks: index_config.yml
  when: mpbn_ip_rm_host.stdout == "master_node"


