- name: configure config_system elastic search
  block:
    - name: edit jvm.options
      shell: sed -i -e 's/-Xms1g/-Xms30g/g' -e 's/-Xmx1g/-Xmx30g/g' /etc/elasticsearch/jvm.options

    - name: edit elasticsearch.yml
      template:
        src: elasticsearch.jinja2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: elasticsearch
        group: elasticsearch
        mode: 0644 
    
    - name: append ulimit
      blockinfile:
        state: present
        insertafter: EOF
        dest: /etc/security/limits.conf
        content: |
          elasticsearch - nofile 65535
          elasticsearch - nproc 4096

    - name: create folder elasticsearch.service.d
      file: 
        path: /etc/systemd/system/elasticsearch.service.d
        mode: 755
        state: directory

    - name: create no limit memory service
      copy:
        dest: "/etc/systemd/system/elasticsearch.service.d/override.conf"
        content: |
          [Service]
          LimitMEMLOCK=infinity
        owner: elasticsearch
        group: elasticsearch
        mode: 0644

    
    - name: add bootstrap password
      shell: echo "{{ bootstrap_password }}" | bin/elasticsearch-keystore add -xf bootstrap.password
      args:
        chdir: {{ es_home }}
      notify:
        - reload systemd
        - enable start-up
        - restart elasticsearch
    
    - name: Flush handlers (force reload-restart elastic search)
      meta: flush_handlers

  become: true
  become_user: root
  tags:
    - sysconfig
