---
# handlers file for elastic-search
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: enable start-up
  ansible.builtin.systemd:
    name: haproxy.service
    enabled: yes

- name: haproxy kibana
  service:
    name: haproxy
    state: restarted
