- name: runtime configuration
  block: 
    - name: "wait for port to be available"
      wait_for:
        host: "{{ master_node }}"
        port: "{{ http_port }}"
        timeout: 10

    - name: create policy remove index
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_ilm/policy/policy__del_after_{{ item }}
        method: PUT
        user: "elastic"
        password: "{{ bootstrap_password }}"
        body: "{{ lookup('template','rm_index.jinja2') | to_json }}"
        body_format: json
        headers:
          Content-Type: "application/json"
      with_items: "{{ policy_setup }}"

    - name: create process index & policy
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_template/{{ item.name | lower }}
        method: PUT
        user: "elastic"
        password: "{{ bootstrap_password }}"
        body: "{{ lookup('template','create_process_index.jinja2') | to_json }}"
        body_format: json
        headers:
          Content-Type: "application/json"
      with_items: "{{ process_index_setup }}"
      
    - name: create index tempalte pattern
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_index_template/template__li_ocs_{{ item.policy | regex_replace('[^0-9]','') }}days
        method: PUT
        user: "elastic"
        password: "{{ bootstrap_password }}"
        body: "{{ lookup('template','index_template_pattern.jinja2') | to_json }}"
        body_format: json
        headers:
          Content-Type: "application/json"
      with_items: "{{ process_index_setup }}"
      
    - name: check cluster settings
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_cluster/settings
        method: GET
        user: "elastic"
        password: "{{ bootstrap_password }}"
        headers:
          Content-Type: "application/json"
      register: cluster_settings

    - debug:
        msg: "Current cluster setting: {{ cluster_settings.json }}"

    - name: set cluster settings to persitent if not
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_cluster/settings
        method: PUT
        user: "elastic"
        password: "{{ bootstrap_password }}"
        body: "{{ lookup('template','deny_remove_all_index.jinja2') | to_json }}"
        body_format: json
        headers:
          Content-Type: "application/json"
      when: "{{ 'persistent' not in cluster_settings.json | to_yaml }}"
  become: true
  become_user: root
  tags:
    - index_config