- name: create user for elastic-search
  block:
    - name: make sure elastic search is up
      wait_for:
        host: "{{ master_node }}"
        port: "{{ http_port }}"
        timeout: 30
        
    - name: List Native Users
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_xpack/security/user
        method: GET
        user: "elastic"
        password: "{{ bootstrap_password }}"
        force_basic_auth: yes
        status_code: 200
      register: user_list_response

    #Set passwords for all users declared - Required as the useradd will not change existing user passwords
    - name: set user passsword
      uri:
        url: http://{{ master_node }}:{{ http_port }}/_security/user/{{ item.name }}/_password
        method: POST
        user: "elastic"
        password: "{{ bootstrap_password }}"
        body: "{{ lookup('template','password.jinja2') | to_json }}"
        body_format: json
        headers:
          Content-Type: "application/json"
        force_basic_auth: yes
        status_code: 200
      with_items: "{{ user_list }}"
  become: true
  become_user: root
  tags:
    - init_user