- name: create user, copy setup file and install elastic search
  block: 
    - name: create user elasticsearch if not exist
      ansible.builtin.user:
        name: elasticsearch
        password: "{{ elasticsearch_passwd }}"
      ignore_errors: yes

    - name: create elasticsearch folder
      shell: |
        mkdir -p /u02/elasticsearch/elasticsearch/;
        chown -R elasticsearch:elasticsearch /u02/elasticsearch;
      ignore_errors: yes
      
    - name: Copy file with owner and permissions
      copy:
        src: "{{ item }}"
        dest: /u02/elasticsearch/elasticsearch/
        owner: elasticsearch
        group: elasticsearch
      with_fileglob: "*.rpm"
      register: rpm_setup_files

    - name: Allow user to have sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^elasticsearch'
        line: 'elasticsearch ALL=(ALL) ALL'
        validate: visudo -cf %s

    - name: install elastic search
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ rpm_setup_files.results | map(attribute='dest') | list }}"

    - name: copy setup file
      shell: |
        cp /etc/elasticsearch/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml_org;
        cp /etc/elasticsearch/jvm.options /etc/elasticsearch/jvm.options_org;

  become: true
  become_user: root
  tags:
    - setup