- name: configure system
  block:

    - name: setsebool connect any
      shell: /usr/sbin/setsebool -P haproxy_connect_any 1

    - name: getsebool
      shell: /usr/sbin/getsebool haproxy_connect_any
      register: getsebool
    
    - debug:
        msg: "Check sebool status: {{ getsebool }}"

    - name: edit haproxy.cfg
      template:
        src: haproxy_cfg.jinja2
        dest: /etc/haproxy/haproxy.cfg
        owner: haproxy
        group: haproxy
        mode: 0644 

    - name: create folder rsyslog.d
      file: 
        path: /etc/rsyslog.d
        mode: 754
        state: directory

    - name: create no limit memory service
      copy:
        dest: "/etc/systemd/system/elasticsearch.service.d/override.conf"
        content: |
          $AddUnixListenSocket /var/lib/haproxy/dev/log
          # Send HAProxy messages to a dedicated logfile
          :programname, startswith, "haproxy" {
            /var/log/haproxy.log
            stop
          }
        mode: 0644
    
    - name: set seLinux to permissive
      shell: |
        sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/sysconfig/selinux;
        sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config;
    
    - name: create logs folder if not exist
      file:
        path: /var/lib/haproxy/dev
        state: directory
        owner: kibana
        group: kibana
        mode: 0755 
      notify:
        - reload systemd
        - restart rsyslog
        - enable start-up
        - restart haproxy
    
    - name: Flush handlers (force reload-restart elastic search)
      meta: flush_handlers

  become: true
  become_user: root
  tags:
    - sysconfig
